# Legacy configuration redirecting google.studentembassador.com to campus.studentembassador.com
server {
    listen 206.81.1.32:80;
    server_name google.studentembassador.com;
    return 308 https://campus.studentembassador.com$request_uri;
}

server {
    listen 206.81.1.32:443 ssl http2;
    server_name google.studentembassador.com;

    ssl_certificate /etc/letsencrypt/live/studentembassador.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studentembassador.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/studentembassador.com/chain.pem;
    include /etc/nginx/snippets/gsa-tls.conf;

    return 308 https://campus.studentembassador.com$request_uri;
}
